### ISSUE TITLE
[bug]: atpull'zi creinstall -q .' in zsh-users/zsh-completions break symlink

### ISSUE THREAD

**Issue by Kritiqual** [z-shell/z-a-meta-plugins#13]
### Environment

OSTYPE=linux-gnu CPUTYPE=x86_64 / MACHINE_TYPE=x86_64 ZSH_VERSION=5.9

### Expected behavior

When install the first time, completions file will be installed like this:

```
$ ls ~/.local/zi/completions

_afew -> ~/.local/zi/plugins/zsh-users---zsh-completions/src/_afew
_android -> ~/.local/zi/plugins/zsh-users---zsh-completions/src/_android
_archlinux-java -> ~.local/zi/plugins/zsh-users---zsh-completions/src/_archlinux-java
...
```

And I expect this still remain after `zi update --all`

### Current behavior

For comparison:
- Normal [1]
```
$ ls ~/.local/zi/completions

_afew -> ~/.local/zi/plugins/zsh-users---zsh-completions/src/_afew
_android -> ~/.local/zi/plugins/zsh-users---zsh-completions/src/_android
_archlinux-java -> ~/.local/zi/plugins/zsh-users---zsh-completions/src/_archlinux-java
```
- Broken [2]
```
$ ls ~/.local/zi/completions

_afew -> ./src/_afew
_android -> ./src/_android
_archlinux-java -> ./src/_archlinux-java
```
Zsh will complain about those broken symlink after next reload

### Steps to reproduce

- Step 1: Install with
```zsh
zi wait lucid light-mode for blockf atpull'zi creinstall -q .' zsh-users/zsh-completions
```

- Step 2: Update with 
```
zi update --all
```
or 
```
zi update zsh-users/zsh-completions
``` 

- Step 3: Broken symlink [2]

### Code snippet

I just pust above install command to .zshrc

### Aditional information

None

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [x] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

**Comment by ss-o** [comment]
Hi @Kritiqual :wave: 

I was able to reproduce the issue on the system where `zsh-users/zsh-completions`  was available on the disk (installed), then re-tried to produce the case with a clean install (`rm -rf ~/.zi; exec zsh -il`), but this time unsuccessfully, and after trying multiple times/methods wasn't able to reproduce the issue.

**Comment by Kritiqual** [comment]
- After clean install (`rm -rf ~/.local/zi` in my case), the issue cannot be reproduce.
- Also, I don't find any problem comes from those directories.
- And, after some test, I found the solution: `zi creinstall -q ..` (notice the `..` at the end, not `.` like original)

**Comment by ss-o** [comment]
Great that the solution was so simple :tada: :dart: However a bit confused about how I was able to reproduce your issue once :hear_no_evil:  Thank you for the confirmation! :handshake:

**Comment by Kritiqual** [comment]
Yeah, the issue only happen when the plugin is previously installed.
Perhaps you can consider making that change into the source, but maybe some more test is needed, idk
